version: '3.9'

volumes:
  sagasu_es: {}
  sagasu_redis: {}
  sagasu_postgres: {}

networks:
  sagasu_net: {}

services:
  redis:
    image: redis:alpine
    container_name: sagasu_redis
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sagasu_net
    volumes:
      - sagasu_redis:/data
    expose: [6379]

  postgres:
    image: postgres:alpine
    container_name: sagasu_postgres
    volumes:
      - sagasu_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sagasu_net
    environment:
      POSTGRES_PASSWORD: password
    expose: [5432]

  elasticsearch:
    container_name: sagasu_es
    build:
      dockerfile: ./docker/elasticsearch.dockerfile
      context: .
    volumes:
      - sagasu_es:/usr/share/elasticsearch/data
    networks:
      - sagasu_net
    env_file:
      - ./docker/elasticsearch.env
    environment:
      discovery.type: single-node
    expose: [9200]

  core:
    container_name: sagasu_core
    build:
      dockerfile: ./docker/core.dockerfile
      context: .
    restart: on-failure
    networks:
      - sagasu_net
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - '127.0.0.1:3000:3000'
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      REDIS_URL: redis://redis:6379
      ES_NODE: http://elasticsearch:9200
