version: '3.9'

volumes:
  sagasu_es: {}
  sagasu_redis: {}
  sagasu_postgres: {}

services:
  redis:
    image: redis:alpine
    container_name: sagasu_redis
    volumes:
      - sagasu_redis:/data
    ports:
      - '6379:6379'

  postgres:
    image: postgres:alpine
    container_name: sagasu_postgres
    volumes:
      - sagasu_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password

  elasticsearch:
    container_name: sagasu_es
    build:
      dockerfile: ./docker/elasticsearch.dockerfile
      context: .
    volumes:
      - sagasu_es:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    environment:
      discovery.type: single-node

  core:
    container_name: sagasu_core
    build:
      dockerfile: ./docker/core.dockerfile
      context: .
    depends_on:
      - redis
      - postgres
      - elasticsearch
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      REDIS_URL: redis://redis:6379
      ES_NODE: http://elasticsearch:9200
